# Generated by Django 2.2.9 on 2020-01-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=35)),
                ('clave', models.CharField(max_length=8)),
                ('rol', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=35)),
                ('edad', models.CharField(max_length=35)),
                ('genero', models.CharField(max_length=35)),
                ('salario', models.CharField(max_length=10)),
            ],
        ),
    ]
